### PR TITLE
Fix parallel cucumber formatter

### PR DESCRIPTION
**Pull request by BillyRuffian**

### CODE REVIEW

**Comment by vveliev-tc** [comment]
try using https://github.com/vveliev-tc/agent-ruby/tree/develop , I may already fix it

**Comment by BillyRuffian** [comment]
Thanks @vveliev-tc I'll take a look. Hopefully it gets merged and published to RubyGems. I'm not able to use GitHub repo as my source for gems because of company policy.

There's a race condition in here too: the `@folder_creation_tracking_file` may not have been created by the time a process want to read from it.

I'm seriously think of just reimplementing this as a new gem.

**Comment by BillyRuffian** [comment]
@vveliev-tc you've added Faraday -- if you really have a dependency on this you should add it as a development / runtime dependency to your .gemspec

Including your branch in my project gives
```
cannot load such file -- faraday (LoadError)
/Users/brooken/.rvm/gems/ruby-2.6.3/bundler/gems/agent-ruby-a64ff9e09490/lib/reportportal.rb:2:in `require'
```

**Comment by vveliev-tc** [comment]
`@folder_creation_tracking_file` - was leftover  and not in use, updated gemspec

**Pull request merged**
